micronaut.application.name = 'lillia'
flyway.datasources.default.enabled = true

[datasources.default]
driver-class-name = 'org.postgresql.Driver'
db-type = 'postgres'

[r2dbc.datasources.default]
dialect = 'POSTGRES'
db-type = 'postgres'

[micronaut.security]
authentication = 'bearer'
token.jwt.signatures.secret.generator.secret = '${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}'

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'
