[micronaut.application]
name = "lillia"

[flyway.datasources.default]
enabled = true

[micronaut.data.pageable]
default-page-size = 24
max-page-size = 240

[micronaut.serde]
date-format = "yyyy-MM-dd'T'HH:mm:ssZ"
deserialization.ignore-unknown = true
serialization.inclusion = "NON_ABSENT"

[datasources.default]
driver-class-name = "org.postgresql.Driver"
db-type = "postgres"
url = "jdbc:postgresql://localhost:5432/lillia_mn_java"
username = "postgres"
password = "postgres"

[r2dbc.datasources.default]
dialect = "POSTGRES"
db-type = "postgres"
url = "r2dbc:postgresql://localhost:5432/lillia_mn_java"
username = "postgres"
password = "postgres"
[option]
driver = "pool"
protocol = "postgres"

#[micronaut.security]
#authentication = "bearer"
#token.jwt.signatures.secret.generator.secret = '${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}'

[micronaut.router.static-resources.swagger]
paths = "classpath:META-INF/swagger"
mapping = "/swagger/**"

[micronaut.router.static-resources.swagger-ui]
paths = "classpath:META-INF/swagger/views/swagger-ui"
mapping = "/swagger-ui/**"
